variable: Logger
settings:
  threshold: TRACE
  callstack:
    max: 5
    start: -1
    stop: -1
levels:
- name: TRACE
  description: This level designates finer-grained informational events than the DEBUG.
  severity: 600
  log_style: !expr crayon::make_style("antiquewhite3")$bold
  msg_style: !expr crayon::make_style('gray60')
- name: DEBUG
  description: This level designates fine-grained informational events that are most useful to debug an application.
  severity: 500
  log_style: !expr crayon::make_style('deepskyblue2')$bold
  msg_style: !expr crayon::make_style('gray90')
- name: INFO
  description: This level designates informational messages that highlight the progress of the application at coarse-grained level.
  severity: 400
  log_style: !expr crayon::make_style('dodgerblue4')$bold
  msg_style: !expr crayon::make_style('gray100')
- name: SUCCESS
  description: This level designates that the operation was unencumbered.
  severity: 300
  log_style: !expr crayon::make_style('chartreuse')$bold
  msg_style: !expr crayon::bgGreen$bold$black
- name: WARN
  description: This level designates potentially harmful situations.
  severity: 350
  log_style: !expr crayon::make_style('darkorange')$bold
  msg_style: !expr crayon::bgYellow$bold$black
- name: ERROR
  description: This level designates error events that might still allow the application to continue running.
  severity: 200
  log_style: !expr crayon::make_style('firebrick1')$bold
  msg_style: !expr crayon::bgBlack$bold$white
- name: FATAL
  description: This level designates very severe error events that will presumably lead the application to abort.
  severity: 100
  log_style: !expr crayon::make_style('firebrick')$bold
  msg_style: !expr crayon::bgRed$bold$white
layouts:
- association: default
  seperator: ' '
  new_line: \n
  formats: new_fmt_log_level(),
           new_fmt_timestamp(crayon::silver$italic),
           new_fmt_log_msg()
- association: level_msg
  seperator: ' '
  new_line: \n
  formats: new_fmt_log_level(),
           new_fmt_log_msg()
